### PR TITLE
data/: Various improvements to adapt to source tree style of other FLOSS projects.

### PR DESCRIPTION
**Pull request by sunweaver**

### CODE REVIEW

**Review by tari01 — APPROVED** [review]
1. Can you please confirm that a raw installation lands everything where it should be? E.g.
```
python3 setup.py build
sudo python3 setup.py install --root=/ --optimize=1
```
2. APPVERSION in ayatanasettings/appdata.py will need to be in sync with the new version in debian/changelog

**Comment by sunweaver** [comment]
> 1. Can you please confirm that a raw installation lands everything where it should be? E.g.
> 
> ```
> python3 setup.py build
> sudo python3 setup.py install --root=/ --optimize=1
> ```

```
[mike@minobo ayatana-settings (pr/data-dir-improvements)]$ python3 setup.py build 
running build
running build_py
creating build
creating build/lib
creating build/lib/ayatanasettings
copying ayatanasettings/__init__.py -> build/lib/ayatanasettings
copying ayatanasettings/logger.py -> build/lib/ayatanasettings
copying ayatanasettings/builder.py -> build/lib/ayatanasettings
copying ayatanasettings/psutil.py -> build/lib/ayatanasettings
copying ayatanasettings/appdata.py -> build/lib/ayatanasettings
[mike@minobo ayatana-settings (pr/data-dir-improvements)]$ sudo python3 setup.py --root=/test --optimize=1
[sudo] password for mike: 
running install
running build
running build_py
running install_lib
creating /test
creating /test/usr
creating /test/usr/local
creating /test/usr/local/lib
creating /test/usr/local/lib/python3.7
creating /test/usr/local/lib/python3.7/dist-packages
creating /test/usr/local/lib/python3.7/dist-packages/ayatanasettings
copying build/lib/ayatanasettings/__init__.py -> /test/usr/local/lib/python3.7/dist-packages/ayatanasettings
copying build/lib/ayatanasettings/logger.py -> /test/usr/local/lib/python3.7/dist-packages/ayatanasettings
copying build/lib/ayatanasettings/builder.py -> /test/usr/local/lib/python3.7/dist-packages/ayatanasettings
copying build/lib/ayatanasettings/psutil.py -> /test/usr/local/lib/python3.7/dist-packages/ayatanasettings
copying build/lib/ayatanasettings/appdata.py -> /test/usr/local/lib/python3.7/dist-packages/ayatanasettings
byte-compiling /test/usr/local/lib/python3.7/dist-packages/ayatanasettings/__init__.py to __init__.cpython-37.pyc
byte-compiling /test/usr/local/lib/python3.7/dist-packages/ayatanasettings/logger.py to logger.cpython-37.pyc
byte-compiling /test/usr/local/lib/python3.7/dist-packages/ayatanasettings/builder.py to builder.cpython-37.pyc
byte-compiling /test/usr/local/lib/python3.7/dist-packages/ayatanasettings/psutil.py to psutil.cpython-37.pyc
byte-compiling /test/usr/local/lib/python3.7/dist-packages/ayatanasettings/appdata.py to appdata.cpython-37.pyc
writing byte-compilation script '/tmp/tmpckbzviw8.py'
/usr/bin/python3 /tmp/tmpckbzviw8.py
removing /tmp/tmpckbzviw8.py
running install_data
creating /test/usr/local/share
creating /test/usr/local/share/icons
creating /test/usr/local/share/icons/hicolor
creating /test/usr/local/share/icons/hicolor/scalable
creating /test/usr/local/share/icons/hicolor/scalable/apps
copying data/icons/hicolor/scalable/apps/ayatana-settings.svg -> /test/usr/local/share/icons/hicolor/scalable/apps
creating /test/usr/local/share/ayatana-settings
copying data/ayatana-settings/ayatana-settings.glade -> /test/usr/local/share/ayatana-settings
creating /test/usr/local/share/applications
copying data/applications/ayatana-settings.desktop -> /test/usr/local/share/applications
copying data/applications/ayatana-settings.desktop.in -> /test/usr/local/share/applications
creating /test/usr/local/bin
copying ayatana-settings -> /test/usr/local/bin/
running install_egg_info
running egg_info
writing ayatana_settings.egg-info/PKG-INFO
writing dependency_links to ayatana_settings.egg-info/dependency_links.txt
writing requirements to ayatana_settings.egg-info/requires.txt
writing top-level names to ayatana_settings.egg-info/top_level.txt
reading manifest file 'ayatana_settings.egg-info/SOURCES.txt'
writing manifest file 'ayatana_settings.egg-info/SOURCES.txt'
Copying ayatana_settings.egg-info to /test/usr/local/lib/python3.7/dist-packages/ayatana_settings-20.10.14.egg-info
running install_scripts
```

gives...

```
[mike@minobo ayatana-settings (pr/data-dir-improvements)]$ tree /test/
/test/
└── usr
    └── local
        ├── bin
        │   └── ayatana-settings
        ├── lib
        │   └── python3.7
        │       └── dist-packages
        │           ├── ayatanasettings
        │           │   ├── appdata.py
        │           │   ├── builder.py
        │           │   ├── __init__.py
        │           │   ├── logger.py
        │           │   ├── psutil.py
        │           │   └── __pycache__
        │           │       ├── appdata.cpython-37.opt-1.pyc
        │           │       ├── appdata.cpython-37.pyc
        │           │       ├── builder.cpython-37.opt-1.pyc
        │           │       ├── builder.cpython-37.pyc
        │           │       ├── __init__.cpython-37.opt-1.pyc
        │           │       ├── __init__.cpython-37.pyc
        │           │       ├── logger.cpython-37.opt-1.pyc
        │           │       ├── logger.cpython-37.pyc
        │           │       ├── psutil.cpython-37.opt-1.pyc
        │           │       └── psutil.cpython-37.pyc
        │           └── ayatana_settings-20.10.14.egg-info
        │               ├── dependency_links.txt
        │               ├── PKG-INFO
        │               ├── requires.txt
        │               ├── SOURCES.txt
        │               └── top_level.txt
        └── share
            ├── applications
            │   ├── ayatana-settings.desktop
            │   └── ayatana-settings.desktop.in
            ├── ayatana-settings
            │   └── ayatana-settings.glade
            └── icons
                └── hicolor
                    └── scalable
                        └── apps
                            └── ayatana-settings.svg

16 directories, 25 files
```

... under Debian buster.

> 1. APPVERSION in ayatanasettings/appdata.py will need to be in sync with the new version in debian/changelog

Yep, I am aware of that.

Mike

**Comment by sunweaver** [comment]
Ah, damn... I need to skip ``ayatana-settings.desktop.in``... Hang on...

**Comment by sunweaver** [comment]
> Ah, damn... I need to skip `ayatana-settings.desktop.in`... Hang on...

Ok, now fixed.

**Comment by sunweaver** [comment]
```
[mike@minobo ayatana-settings (pr/data-dir-improvements)]$ tree /test/
/test/
└── usr
    └── local
        ├── bin
        │   └── ayatana-settings
        ├── lib
        │   └── python3.7
        │       └── dist-packages
        │           ├── ayatanasettings
        │           │   ├── appdata.py
        │           │   ├── builder.py
        │           │   ├── __init__.py
        │           │   ├── logger.py
        │           │   ├── psutil.py
        │           │   └── __pycache__
        │           │       ├── appdata.cpython-37.opt-1.pyc
        │           │       ├── appdata.cpython-37.pyc
        │           │       ├── builder.cpython-37.opt-1.pyc
        │           │       ├── builder.cpython-37.pyc
        │           │       ├── __init__.cpython-37.opt-1.pyc
        │           │       ├── __init__.cpython-37.pyc
        │           │       ├── logger.cpython-37.opt-1.pyc
        │           │       ├── logger.cpython-37.pyc
        │           │       ├── psutil.cpython-37.opt-1.pyc
        │           │       └── psutil.cpython-37.pyc
        │           └── ayatana_settings-20.10.14.egg-info
        │               ├── dependency_links.txt
        │               ├── PKG-INFO
        │               ├── requires.txt
        │               ├── SOURCES.txt
        │               └── top_level.txt
        └── share
            ├── applications
            │   └── ayatana-settings.desktop
            ├── ayatana-settings
            │   └── ayatana-settings.glade
            └── icons
                └── hicolor
                    └── scalable
                        └── apps
                            └── ayatana-settings.svg

16 directories, 24 files
```

**Pull request merged**
